### ISSUE TITLE
programar bien el status del invoice

### ISSUE THREAD

**Issue by peillis** [peillis/siwapp#116]
Ahora mismo es demasiado simple. Aquí está el código actual de ruby:

```ruby
def get_status
    if draft
      :draft
    elsif failed
      :failed
    elsif paid
      :paid
    elsif due_date
      if due_date > Date.current
        :pending
      else
        :past_due
      end
    else
      # An invoice without a due date can't be past_due
      :pending
    end
  end
```

**Comment by Pabloj20** [comment]
Si el status de una invoice es draft o failed, ¿esa invoice no debe aparecer en la lista de invoices o sí debe aparecer pero con la etiqueta draft o failed?

**Comment by peillis** [comment]
Debe aparecer con la etiqueta que corresponda si.
