### ISSUE TITLE
definir el @type t para Item y añadir specs a sus funciones

### ISSUE THREAD

**Issue by peillis** [peillis/siwapp#129]

**Comment by Pabloj20** [comment]
Enrique una pregunta. ¿Tengo que añadir specs solamente a las funciones que hemos creado manualmente o también a las que se generaban con el mix.gen?

**Comment by peillis** [comment]
no sé a cuales te refieres, dime más en concreto y te digo

**Comment by Pabloj20** [comment]
a las fn create, update, delete y get

**Comment by Pabloj20** [comment]
mas bien las 3 primeras ya que get sí está modificado

**Comment by peillis** [comment]
si, todas esas si

**Comment by Pabloj20** [comment]
vale lo he subido, asi que lo añado y vuelvo a hacer el pr
