### ISSUE TITLE
work in a query module for invoices

### ISSUE THREAD

**Issue by peillis** [peillis/siwapp#65]
so we could compose different queries via pipes

**Comment by RodrigoMolinaMadrid** [comment]
Creo que primero debería empezar el módulo de querys para customers. Las necesarias para las CRUD operations para customers.

**Comment by peillis** [comment]
ok, aunque no veo yo que tenga mucha complejidad las queries de customer, no sé si va a dar como para un módulo

**Comment by RodrigoMolinaMadrid** [comment]
Vale, si veo que se me queda muy pequeño, ¿meto las querys de customer dentro del módulo de querys de invoices o las hago como funciones dentro del schema como dice en el artículo que me enviaste? https://learn-elixir.dev/blogs/creating-reusable-ecto-code

**Comment by peillis** [comment]
dentro del schema mejor
