### ISSUE TITLE
new invoice button, make it change depending on context

### ISSUE THREAD

**Issue by peillis** [peillis/siwapp#82]

**Comment by Pabloj20** [comment]
aquí se verá mejor
![Uploading Captura de pantalla de 2022-01-04 13-14-08.png…]()

**Comment by Pabloj20** [comment]
aquí se verá mejor
![Captura de pantalla de 2022-01-04 13-14-08](https://user-images.githubusercontent.com/66000403/148058738-fbbfba60-fd68-42e5-84db-d29ade870740.png)

**Comment by peillis** [comment]
No sé, busca la mejor opción. A lo mejor puede ser una función que lea @page_title como parámetro.

**Comment by Pabloj20** [comment]
Enrique ya lo he solucionado. Hago también el buscador que hay en siwapp hecho con Ruby o solamente el botón??

**Comment by peillis** [comment]
Sólo el botón
